### ISSUE TITLE
'Icon' is not exported from 'antd'

### ISSUE THREAD

**Issue by taejin5314** [jaewonhimnae/boilerplate-mern-stack#19]
'Icon' is not exported from 'antd'

from Footer.js, LoginPage.js, NavBar.js

**Comment by Darshak-Bali** [comment]
what was the problem with Icon
Can u tell how to solved it

**Comment by taejin5314** [comment]
Umm.. it was like 4 months ago, so I can't remember how exactly I solve that. But I think you can use `@ant-design/icons`.
`npm install @ant-design/icons` then import whatever icons you need from `@ant-design/icons`.

ex) `import { SmileOutline, SmileOutlined } from '@ant-design/icons';`

I hope that this would help you to solve the problem. :)

**Comment by anxiubin** [comment]
"icon issue" occured because of version difference.
Plz check [this](https://ant.design/docs/react/migration-v4#Icon-upgrade) out :)
This document will help you upgrade from antd 3.x version to antd 4.x version
