### ISSUE TITLE
Cannot register from client or server.

### ISSUE THREAD

**Issue by arsalansadiq** [jaewonhimnae/boilerplate-mern-stack#27]
Whenever I try to submit with information (I have my mongodb connected): It gives this error
`[HPM] Error occurred while trying to proxy request /api/users/register from localhost:3000 to http://localhost:5000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

on the browser, it shows a 504 error.

All I did was to npm install in client and root and added dev.js with 
`mongodb://<Username>:<password>@<ClusterInfo>/<dbname>?ssl=true&replicaSet=<ClusterName>&authSource=admin&retryWrites=true&w=majority`

and ran `npm run dev`

not sure where I am wrong, can you help me on this.

**Comment by icatalyse** [comment]
I GOT THE APP RUNNING ON MY BROWSER BUT I CAN'T SIGN IN OR SIGN UP.... THIS MAKES IT IMPOSSIBLE TO VIEW THE PROGRESS OF THE APP.
PLEASE!!! HELP...

**Comment by AWAIS97** [comment]
change the port from 5000 to something else (I just did 8080) on your local /.env file

I think port 5000 was conflicting with something else running on my machine, probably the same for you.
or 
Happens when you forgot to put http:// but instead just typed localhost:5000

**Comment by AWAIS97** [comment]
change the port from 5000 to something else (I just did 8080) on your local /.env file

I think port 5000 was conflicting with something else running on my machine, probably the same for you.
or
Happens when you forgot to put http:// but instead just typed localhost:5000

or 
did you include the key of mongodb in index.js

**Comment by arsalansadiq** [comment]
@AWAIS97 Thank You, changing the listening port worked for me! Cheers and kudos for the help.
