### ISSUE TITLE
I don't understand the validation about register module,

### ISSUE THREAD

**Issue by HomyeeKing** [jaewonhimnae/boilerplate-mern-stack#33]
```js
if (user.isModified('password')) {
		bcrypt.genSalt(10, (err, salt) => {
			if (err) return next(err)
			bcrypt.hash(user.password, salt, (err, hash) => {
				if (err) return next(err)
				user.password = hash
				next()
			})
		})
	} else {
		next()
	}
```

I can't understand why use `isModified` to judge if there's already have the account,

**Comment by AWAIS97** [comment]
This is used when user want to change its password.
So, `isModified function` used in pre-save data.

We also can you findAndUpdated method for better understanding. check the link for for more.
https://stackoverflow.com/questions/50581825/ismodified-and-pre-save-mongoose-nodejs

**Comment by HomyeeKing** [comment]
@AWAIS97  OK, maybe  I thought it was called after the  user register the account at that time, now I review the code, it's clear now, thx for ur reply
